Ravens Robotics FRC 2015: Robot Class Reference
Robot Class Reference
Public Member Functions
Robot ()
Private Member Functions
void RobotInit ()
void DisabledInit ()
void DisabledPeriodic ()
void AutonomousInit ()
void AutonomousPeriodic ()
void TeleopInit ()
void TeleopPeriodic ()
void TestInit ()
void TestPeriodic ()
Private Attributes
Camera m_Camera
Camera RobotComponent.
MecanumDrive m_Drive
MecanumDrive RobotComponent.
Encoder encoder
Ultrasonic Sonic
DigitalInput bottomSwitch
DigitalInput topSwitch
DigitalInput frontSwitch
LiveWindow * lw
int autoLoopCounter
Detailed Description
Definition at line 6 of file Robot.cpp.
Constructor & Destructor Documentation
Robot::Robot () inline
Constructor - According to the docs for IterativeRobot, the initialization being done here should instead be in a RobotInit() function, to ensure that all base-level init is completed before we try using any hardware.
Definition at line 26 of file Robot.cpp.
Member Function Documentation
void Robot::AutonomousInit () inline private
AutonomousInit() – called each and every time autonomous is entered from another mode
Definition at line 66 of file Robot.cpp.
void Robot::AutonomousPeriodic () inline private
AutonomousPeriodic() – called periodically during autonomous phase.
Periodic() functions – each of these functions is called iteratively at the appropriate periodic rate (aka the "slow loop"). The default period of the iterative robot is synced to the driver station control packets, giving a periodic frequency of about 50Hz (50 times per second).
Definition at line 81 of file Robot.cpp.
void Robot::DisabledInit () inline private
DisabledInit() – called only when first disabled
Definition at line 51 of file Robot.cpp.
void Robot::DisabledPeriodic () inline private
DisabledPeriodic() – called periodically during disabled phase
Definition at line 58 of file Robot.cpp.
void Robot::RobotInit () inline private
RobotInit() – provide for initialization at robot power-on
Definition at line 41 of file Robot.cpp.
References Camera::ComponentInit(), and MecanumDrive::ComponentInit().
void Robot::TeleopInit () inline private
TeleopInit() – called each and every time teleop is entered from another mode
Definition at line 95 of file Robot.cpp.
void Robot::TeleopPeriodic () inline private
< Divides the value taken from the encoder by gear ratio of 71.164, it then divides the result by encoder ratio of 7:1, it will output the # of motor rotations.
Definition at line 102 of file Robot.cpp.
References Camera::DoWork(), MecanumDrive::DoWork(), Camera::Sense(), and MecanumDrive::Sense().
void Robot::TestInit () inline private
TestInit() – called each and every time test is entered from another mode
Definition at line 172 of file Robot.cpp.
void Robot::TestPeriodic () inline private
TestPeriodic() – called periodically during test phase.
Definition at line 179 of file Robot.cpp.
Member Data Documentation
int Robot::autoLoopCounter private
Definition at line 18 of file Robot.cpp.
DigitalInput Robot::bottomSwitch private
Definition at line 14 of file Robot.cpp.
Encoder Robot::encoder private
Definition at line 12 of file Robot.cpp.
DigitalInput Robot::frontSwitch private
Definition at line 16 of file Robot.cpp.
LiveWindow* Robot::lw private
Definition at line 17 of file Robot.cpp.
Camera Robot::m_Camera private
Camera RobotComponent.
Definition at line 9 of file Robot.cpp.
MecanumDrive Robot::m_Drive private
MecanumDrive RobotComponent.
Definition at line 10 of file Robot.cpp.
Ultrasonic Robot::Sonic private
Definition at line 13 of file Robot.cpp.
DigitalInput Robot::topSwitch private
Definition at line 15 of file Robot.cpp.
The documentation for this class was generated from the following file:
src/Robot.cpp